version: 2
jobs:
  build:
    docker:
      - image: pandoc/latex

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command:
            apk add make texlive-xetex ttf-dejavu

      - run:
          name: Build all formats
          command:
            make epub

      - run:
          name: Check if epub exists
          command:
            test -s build/epub/book.epub
