name: Review

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Environment directory
        run: echo "FILE_LIST=$(printf '"%s" ' chapters/*.md)" >> $GITHUB_ENV
      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            --toc
            --toc-depth=2
            --webtex
            --css=style.css
            --metadata-file=metadata.yml
            --wrap=none
            --epub-cover-image=images/cover.png
            -o ebook.epub
            ${{ env.FILE_LIST }}
      - name: Upload Pull Request Asset
        uses: actions/upload-artifact@master
        with:
          name: ebook.epub
          path: ./ebook.epub
      - uses: actions/download-artifact@master
        with:
          name: ebook.epub
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ebook.epub